framework:
    workflows:
        content_publishing:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - Morfeditorial\MachinimaCoreBundle\Model\ContentItem
            places:
                - draft
                - review
                - pending_review
                - published
                - rejected
            transitions:
                submit:
                    from: draft
                    to: review
                publish:
                    from: review
                    to: published
                reject:
                    from: [review, pending_review]
                    to: rejected
                redraft:
                    from: [review, rejected, pending_review]
                    to: draft
